### ISSUE TITLE
npm run  db-migrate  （迁移创建表有问题，是不是users的迁移语法不对呀）

### ISSUE THREAD

**Issue by wwb568109135** [Imfdj/egg-beehive#8]
10011364@WWB-10011364 MINGW64 /e/demo/egg-beehive (main)
$ npm run  db-migrate

> egg-beehive@1.0.0 db-migrate
> sequelize db:migrate

Sequelize CLI [Node: 16.13.0, CLI: 5.5.1, ORM: 5.22.5]

Loaded configuration file "database\config.json".
Using environment "development".
== 20200110080210-create-invite: migrating =======

ERROR: Failed to open the referenced table 'users'

**Comment by Imfdj** [comment]
应该是 migrations 文件夹下的 文件顺序，影响了20200110080210-create-invite创建时的外键引用，导致的失败。可以调整一下，但没必要。
如果你是要初始化数据库，推荐：将database目录下的egg-beehive-dev.sql和egg-beehive-test.sql导入mysql（推荐navicat）。

**Comment by wwb568109135** [comment]
ok
